### ISSUE TITLE
Overflow when Fullscreen Window

### ISSUE THREAD

**Issue by HerXayah** [pykeio/vibe#2]
![unknown (13)](https://user-images.githubusercontent.com/45071533/193426834-9a3595fd-ee89-4f88-8a4b-e625ca40e69e.png)

**Comment by decahedron1** [comment]
What version of Windows are you running? Sorry for the late reply.

**Comment by HerXayah** [comment]
> What version of Windows are you running? Sorry for the late reply.

11

**Comment by decahedron1** [comment]
What's the OS build number? You can find the build number in Settings > System > About, under "OS build".

**Comment by HerXayah** [comment]
> What's the OS build number? You can find the build number in Settings > System > About, under "OS build".

![image](https://user-images.githubusercontent.com/45071533/193431407-b18d7e66-8656-4835-ab63-bb82d157a7cf.png)

**Comment by decahedron1** [comment]
Hm, 22000.1042 surprisingly does not support system backdrop types. The Mica effect was available since 22000 through an undocumented API, but the Acrylic effect was either not implemented for Win32 apps or simply never discovered, so this uses an old style of acrylic (I believe from the Windows 8 days).

Maybe try setting `frame: false`? Though it should be noted that this will break effects on Windows 11 Insiders builds over 22523 and the upcoming 22H2 release, so it should be behind a check or option of some sorts.

**Comment by HerXayah** [comment]
> Hm, 22000.1042 surprisingly does not support system backdrop types. The Mica effect was available since 22000 through an undocumented API, but the Acrylic effect was either not implemented for Win32 apps or simply never discovered, so this uses an old style of acrylic (I believe from the Windows 8 days).
> 
> Maybe try setting `frame: false`? Though it should be noted that this will break effects on Windows 11 Insiders builds over 22523 and the upcoming 22H2 release, so it should be behind a check or option of some sorts.

Im using OpenAsar one which is Acrylic btw ^-^

EDIT:

There is also some weird issue sometimes when beeing fullscreen at startup where you would need to resize the window for it to work properly
